//
// File generated by rootcint at Fri Nov 24 11:36:36 2017

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME PMAnaSummaryDict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "PMAnaSummaryDict.h"

#include "TCollectionProxyInfo.h"
#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TInterpreter.h"
#include "TVirtualMutex.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOTShadow {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOTShadow
// END OF SHADOWS

namespace ROOTDict {
   void PMAnaSummary_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_PMAnaSummary(void *p = 0);
   static void *newArray_PMAnaSummary(Long_t size, void *p);
   static void delete_PMAnaSummary(void *p);
   static void deleteArray_PMAnaSummary(void *p);
   static void destruct_PMAnaSummary(void *p);
   static void streamer_PMAnaSummary(TBuffer &buf, void *obj);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const ::PMAnaSummary*)
   {
      ::PMAnaSummary *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::PMAnaSummary >(0);
      static ::ROOT::TGenericClassInfo 
         instance("PMAnaSummary", ::PMAnaSummary::Class_Version(), "././PMAnaSummary.h", 20,
                  typeid(::PMAnaSummary), ::ROOT::DefineBehavior(ptr, ptr),
                  &::PMAnaSummary::Dictionary, isa_proxy, 0,
                  sizeof(::PMAnaSummary) );
      instance.SetNew(&new_PMAnaSummary);
      instance.SetNewArray(&newArray_PMAnaSummary);
      instance.SetDelete(&delete_PMAnaSummary);
      instance.SetDeleteArray(&deleteArray_PMAnaSummary);
      instance.SetDestructor(&destruct_PMAnaSummary);
      instance.SetStreamerFunc(&streamer_PMAnaSummary);
      return &instance;
   }
   ROOT::TGenericClassInfo *GenerateInitInstance(const ::PMAnaSummary*)
   {
      return GenerateInitInstanceLocal((::PMAnaSummary*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::PMAnaSummary*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOTDict

//______________________________________________________________________________
atomic_TClass_ptr PMAnaSummary::fgIsA(0);  // static to hold class pointer

//______________________________________________________________________________
const char *PMAnaSummary::Class_Name()
{
   return "PMAnaSummary";
}

//______________________________________________________________________________
const char *PMAnaSummary::ImplFileName()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::PMAnaSummary*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int PMAnaSummary::ImplFileLine()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::PMAnaSummary*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void PMAnaSummary::Dictionary()
{
   fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::PMAnaSummary*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *PMAnaSummary::Class()
{
   if (!fgIsA) { R__LOCKGUARD2(gCINTMutex); if(!fgIsA) {fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::PMAnaSummary*)0x0)->GetClass();} }
   return fgIsA;
}

//______________________________________________________________________________
void PMAnaSummary::Streamer(TBuffer &R__b)
{
   // Stream an object of class PMAnaSummary.

   UInt_t R__s, R__c;
   if (R__b.IsReading()) {
      Version_t R__v = R__b.ReadVersion(&R__s, &R__c); if (R__v) { }
      TObject::Streamer(R__b);
      R__b >> Ntrack;
      R__b >> Ningtrack;
      R__b >> clstime;
      R__b >> clstimecorr;
      R__b >> exptime;
      R__b >> hitcyc;
      R__b >> ontime;
      R__b >> vetowtracking;
      R__b >> edgewtracking;
      R__b.ReadStaticArray((float*)vact);
      {
         vector<Float_t> &R__stl =  x;
         R__stl.clear();
         int R__i, R__n;
         R__b >> R__n;
         R__stl.reserve(R__n);
         for (R__i = 0; R__i < R__n; R__i++) {
            float R__t;
            R__b >> R__t;
            R__stl.push_back(R__t);
         }
      }
      {
         vector<Float_t> &R__stl =  y;
         R__stl.clear();
         int R__i, R__n;
         R__b >> R__n;
         R__stl.reserve(R__n);
         for (R__i = 0; R__i < R__n; R__i++) {
            float R__t;
            R__b >> R__t;
            R__stl.push_back(R__t);
         }
      }
      {
         vector<Float_t> &R__stl =  z;
         R__stl.clear();
         int R__i, R__n;
         R__b >> R__n;
         R__stl.reserve(R__n);
         for (R__i = 0; R__i < R__n; R__i++) {
            float R__t;
            R__b >> R__t;
            R__stl.push_back(R__t);
         }
      }
      {
         vector<Float_t> &R__stl =  zx;
         R__stl.clear();
         int R__i, R__n;
         R__b >> R__n;
         R__stl.reserve(R__n);
         for (R__i = 0; R__i < R__n; R__i++) {
            float R__t;
            R__b >> R__t;
            R__stl.push_back(R__t);
         }
      }
      {
         vector<Float_t> &R__stl =  zy;
         R__stl.clear();
         int R__i, R__n;
         R__b >> R__n;
         R__stl.reserve(R__n);
         for (R__i = 0; R__i < R__n; R__i++) {
            float R__t;
            R__b >> R__t;
            R__stl.push_back(R__t);
         }
      }
      {
         vector<Int_t> &R__stl =  startxpln;
         R__stl.clear();
         int R__i, R__n;
         R__b >> R__n;
         R__stl.reserve(R__n);
         for (R__i = 0; R__i < R__n; R__i++) {
            int R__t;
            R__b >> R__t;
            R__stl.push_back(R__t);
         }
      }
      {
         vector<Int_t> &R__stl =  startypln;
         R__stl.clear();
         int R__i, R__n;
         R__b >> R__n;
         R__stl.reserve(R__n);
         for (R__i = 0; R__i < R__n; R__i++) {
            int R__t;
            R__b >> R__t;
            R__stl.push_back(R__t);
         }
      }
      {
         vector<Float_t> &R__stl =  startxch;
         R__stl.clear();
         int R__i, R__n;
         R__b >> R__n;
         R__stl.reserve(R__n);
         for (R__i = 0; R__i < R__n; R__i++) {
            float R__t;
            R__b >> R__t;
            R__stl.push_back(R__t);
         }
      }
      {
         vector<Float_t> &R__stl =  startych;
         R__stl.clear();
         int R__i, R__n;
         R__b >> R__n;
         R__stl.reserve(R__n);
         for (R__i = 0; R__i < R__n; R__i++) {
            float R__t;
            R__b >> R__t;
            R__stl.push_back(R__t);
         }
      }
      {
         vector<Int_t> &R__stl =  endxpln;
         R__stl.clear();
         int R__i, R__n;
         R__b >> R__n;
         R__stl.reserve(R__n);
         for (R__i = 0; R__i < R__n; R__i++) {
            int R__t;
            R__b >> R__t;
            R__stl.push_back(R__t);
         }
      }
      {
         vector<Int_t> &R__stl =  endypln;
         R__stl.clear();
         int R__i, R__n;
         R__b >> R__n;
         R__stl.reserve(R__n);
         for (R__i = 0; R__i < R__n; R__i++) {
            int R__t;
            R__b >> R__t;
            R__stl.push_back(R__t);
         }
      }
      {
         vector<Float_t> &R__stl =  endxch;
         R__stl.clear();
         int R__i, R__n;
         R__b >> R__n;
         R__stl.reserve(R__n);
         for (R__i = 0; R__i < R__n; R__i++) {
            float R__t;
            R__b >> R__t;
            R__stl.push_back(R__t);
         }
      }
      {
         vector<Float_t> &R__stl =  endych;
         R__stl.clear();
         int R__i, R__n;
         R__b >> R__n;
         R__stl.reserve(R__n);
         for (R__i = 0; R__i < R__n; R__i++) {
            float R__t;
            R__b >> R__t;
            R__stl.push_back(R__t);
         }
      }
      {
         vector<Float_t> &R__stl =  thetax;
         R__stl.clear();
         int R__i, R__n;
         R__b >> R__n;
         R__stl.reserve(R__n);
         for (R__i = 0; R__i < R__n; R__i++) {
            float R__t;
            R__b >> R__t;
            R__stl.push_back(R__t);
         }
      }
      {
         vector<Float_t> &R__stl =  thetay;
         R__stl.clear();
         int R__i, R__n;
         R__b >> R__n;
         R__stl.reserve(R__n);
         for (R__i = 0; R__i < R__n; R__i++) {
            float R__t;
            R__b >> R__t;
            R__stl.push_back(R__t);
         }
      }
      {
         vector<Float_t> &R__stl =  angle;
         R__stl.clear();
         int R__i, R__n;
         R__b >> R__n;
         R__stl.reserve(R__n);
         for (R__i = 0; R__i < R__n; R__i++) {
            float R__t;
            R__b >> R__t;
            R__stl.push_back(R__t);
         }
      }
      {
         vector<Int_t> &R__stl =  ing_startmod;
         R__stl.clear();
         int R__i, R__n;
         R__b >> R__n;
         R__stl.reserve(R__n);
         for (R__i = 0; R__i < R__n; R__i++) {
            int R__t;
            R__b >> R__t;
            R__stl.push_back(R__t);
         }
      }
      {
         vector<Int_t> &R__stl =  ing_endmod;
         R__stl.clear();
         int R__i, R__n;
         R__b >> R__n;
         R__stl.reserve(R__n);
         for (R__i = 0; R__i < R__n; R__i++) {
            int R__t;
            R__b >> R__t;
            R__stl.push_back(R__t);
         }
      }
      {
         vector<Int_t> &R__stl =  ing_startpln;
         R__stl.clear();
         int R__i, R__n;
         R__b >> R__n;
         R__stl.reserve(R__n);
         for (R__i = 0; R__i < R__n; R__i++) {
            int R__t;
            R__b >> R__t;
            R__stl.push_back(R__t);
         }
      }
      {
         vector<Int_t> &R__stl =  ing_endpln;
         R__stl.clear();
         int R__i, R__n;
         R__b >> R__n;
         R__stl.reserve(R__n);
         for (R__i = 0; R__i < R__n; R__i++) {
            int R__t;
            R__b >> R__t;
            R__stl.push_back(R__t);
         }
      }
      {
         vector<Bool_t> &R__stl =  ing_trk;
         R__stl.clear();
         int R__i, R__n;
         R__b >> R__n;
         R__stl.reserve(R__n);
         for (R__i = 0; R__i < R__n; R__i++) {
            bool R__t;
            R__b >> R__t;
            R__stl.push_back(R__t);
         }
      }
      {
         vector<Bool_t> &R__stl =  pm_stop;
         R__stl.clear();
         int R__i, R__n;
         R__b >> R__n;
         R__stl.reserve(R__n);
         for (R__i = 0; R__i < R__n; R__i++) {
            bool R__t;
            R__b >> R__t;
            R__stl.push_back(R__t);
         }
      }
      {
         vector<Bool_t> &R__stl =  ing_stop;
         R__stl.clear();
         int R__i, R__n;
         R__b >> R__n;
         R__stl.reserve(R__n);
         for (R__i = 0; R__i < R__n; R__i++) {
            bool R__t;
            R__b >> R__t;
            R__stl.push_back(R__t);
         }
      }
      {
         vector<Float_t> &R__stl =  sci_range;
         R__stl.clear();
         int R__i, R__n;
         R__b >> R__n;
         R__stl.reserve(R__n);
         for (R__i = 0; R__i < R__n; R__i++) {
            float R__t;
            R__b >> R__t;
            R__stl.push_back(R__t);
         }
      }
      {
         vector<Float_t> &R__stl =  iron_range;
         R__stl.clear();
         int R__i, R__n;
         R__b >> R__n;
         R__stl.reserve(R__n);
         for (R__i = 0; R__i < R__n; R__i++) {
            float R__t;
            R__b >> R__t;
            R__stl.push_back(R__t);
         }
      }
      {
         vector<Int_t> &R__stl =  iron_pene;
         R__stl.clear();
         int R__i, R__n;
         R__b >> R__n;
         R__stl.reserve(R__n);
         for (R__i = 0; R__i < R__n; R__i++) {
            int R__t;
            R__b >> R__t;
            R__stl.push_back(R__t);
         }
      }
      {
         vector<Bool_t> &R__stl =  veto;
         R__stl.clear();
         int R__i, R__n;
         R__b >> R__n;
         R__stl.reserve(R__n);
         for (R__i = 0; R__i < R__n; R__i++) {
            bool R__t;
            R__b >> R__t;
            R__stl.push_back(R__t);
         }
      }
      {
         vector<Bool_t> &R__stl =  edge;
         R__stl.clear();
         int R__i, R__n;
         R__b >> R__n;
         R__stl.reserve(R__n);
         for (R__i = 0; R__i < R__n; R__i++) {
            bool R__t;
            R__b >> R__t;
            R__stl.push_back(R__t);
         }
      }
      {
         vector<Int_t> &R__stl =  pdg;
         R__stl.clear();
         int R__i, R__n;
         R__b >> R__n;
         R__stl.reserve(R__n);
         for (R__i = 0; R__i < R__n; R__i++) {
            int R__t;
            R__b >> R__t;
            R__stl.push_back(R__t);
         }
      }
      {
         vector<Float_t> &R__stl =  mucl;
         R__stl.clear();
         int R__i, R__n;
         R__b >> R__n;
         R__stl.reserve(R__n);
         for (R__i = 0; R__i < R__n; R__i++) {
            float R__t;
            R__b >> R__t;
            R__stl.push_back(R__t);
         }
      }
      {
         vector<Float_t> &R__stl =  trkpe;
         R__stl.clear();
         int R__i, R__n;
         R__b >> R__n;
         R__stl.reserve(R__n);
         for (R__i = 0; R__i < R__n; R__i++) {
            float R__t;
            R__b >> R__t;
            R__stl.push_back(R__t);
         }
      }
      R__b >> nhits;
      R__b.ReadStaticArray((int*)nhitTs);
      int R__i;
      for (R__i = 0; R__i < 1000; R__i++)
         fIngridHit[R__i].Streamer(R__b);
      for (R__i = 0; R__i < 10; R__i++)
         fTrack[R__i].Streamer(R__b);
      for (R__i = 0; R__i < 10000; R__i++)
         fIngridHitTrk[0][R__i].Streamer(R__b);
      R__b >> ntracks;
      R__b.CheckByteCount(R__s, R__c, PMAnaSummary::IsA());
   } else {
      R__c = R__b.WriteVersion(PMAnaSummary::IsA(), kTRUE);
      TObject::Streamer(R__b);
      R__b << Ntrack;
      R__b << Ningtrack;
      R__b << clstime;
      R__b << clstimecorr;
      R__b << exptime;
      R__b << hitcyc;
      R__b << ontime;
      R__b << vetowtracking;
      R__b << edgewtracking;
      R__b.WriteArray(vact, 100);
      {
         vector<Float_t> &R__stl =  x;
         int R__n=(true) ? int(R__stl.size()) : 0;
         R__b << R__n;
         if(R__n) {
            vector<Float_t>::iterator R__k;
            for (R__k = R__stl.begin(); R__k != R__stl.end(); ++R__k) {
            R__b << (*R__k);
            }
         }
      }
      {
         vector<Float_t> &R__stl =  y;
         int R__n=(true) ? int(R__stl.size()) : 0;
         R__b << R__n;
         if(R__n) {
            vector<Float_t>::iterator R__k;
            for (R__k = R__stl.begin(); R__k != R__stl.end(); ++R__k) {
            R__b << (*R__k);
            }
         }
      }
      {
         vector<Float_t> &R__stl =  z;
         int R__n=(true) ? int(R__stl.size()) : 0;
         R__b << R__n;
         if(R__n) {
            vector<Float_t>::iterator R__k;
            for (R__k = R__stl.begin(); R__k != R__stl.end(); ++R__k) {
            R__b << (*R__k);
            }
         }
      }
      {
         vector<Float_t> &R__stl =  zx;
         int R__n=(true) ? int(R__stl.size()) : 0;
         R__b << R__n;
         if(R__n) {
            vector<Float_t>::iterator R__k;
            for (R__k = R__stl.begin(); R__k != R__stl.end(); ++R__k) {
            R__b << (*R__k);
            }
         }
      }
      {
         vector<Float_t> &R__stl =  zy;
         int R__n=(true) ? int(R__stl.size()) : 0;
         R__b << R__n;
         if(R__n) {
            vector<Float_t>::iterator R__k;
            for (R__k = R__stl.begin(); R__k != R__stl.end(); ++R__k) {
            R__b << (*R__k);
            }
         }
      }
      {
         vector<Int_t> &R__stl =  startxpln;
         int R__n=(true) ? int(R__stl.size()) : 0;
         R__b << R__n;
         if(R__n) {
            vector<Int_t>::iterator R__k;
            for (R__k = R__stl.begin(); R__k != R__stl.end(); ++R__k) {
            R__b << (*R__k);
            }
         }
      }
      {
         vector<Int_t> &R__stl =  startypln;
         int R__n=(true) ? int(R__stl.size()) : 0;
         R__b << R__n;
         if(R__n) {
            vector<Int_t>::iterator R__k;
            for (R__k = R__stl.begin(); R__k != R__stl.end(); ++R__k) {
            R__b << (*R__k);
            }
         }
      }
      {
         vector<Float_t> &R__stl =  startxch;
         int R__n=(true) ? int(R__stl.size()) : 0;
         R__b << R__n;
         if(R__n) {
            vector<Float_t>::iterator R__k;
            for (R__k = R__stl.begin(); R__k != R__stl.end(); ++R__k) {
            R__b << (*R__k);
            }
         }
      }
      {
         vector<Float_t> &R__stl =  startych;
         int R__n=(true) ? int(R__stl.size()) : 0;
         R__b << R__n;
         if(R__n) {
            vector<Float_t>::iterator R__k;
            for (R__k = R__stl.begin(); R__k != R__stl.end(); ++R__k) {
            R__b << (*R__k);
            }
         }
      }
      {
         vector<Int_t> &R__stl =  endxpln;
         int R__n=(true) ? int(R__stl.size()) : 0;
         R__b << R__n;
         if(R__n) {
            vector<Int_t>::iterator R__k;
            for (R__k = R__stl.begin(); R__k != R__stl.end(); ++R__k) {
            R__b << (*R__k);
            }
         }
      }
      {
         vector<Int_t> &R__stl =  endypln;
         int R__n=(true) ? int(R__stl.size()) : 0;
         R__b << R__n;
         if(R__n) {
            vector<Int_t>::iterator R__k;
            for (R__k = R__stl.begin(); R__k != R__stl.end(); ++R__k) {
            R__b << (*R__k);
            }
         }
      }
      {
         vector<Float_t> &R__stl =  endxch;
         int R__n=(true) ? int(R__stl.size()) : 0;
         R__b << R__n;
         if(R__n) {
            vector<Float_t>::iterator R__k;
            for (R__k = R__stl.begin(); R__k != R__stl.end(); ++R__k) {
            R__b << (*R__k);
            }
         }
      }
      {
         vector<Float_t> &R__stl =  endych;
         int R__n=(true) ? int(R__stl.size()) : 0;
         R__b << R__n;
         if(R__n) {
            vector<Float_t>::iterator R__k;
            for (R__k = R__stl.begin(); R__k != R__stl.end(); ++R__k) {
            R__b << (*R__k);
            }
         }
      }
      {
         vector<Float_t> &R__stl =  thetax;
         int R__n=(true) ? int(R__stl.size()) : 0;
         R__b << R__n;
         if(R__n) {
            vector<Float_t>::iterator R__k;
            for (R__k = R__stl.begin(); R__k != R__stl.end(); ++R__k) {
            R__b << (*R__k);
            }
         }
      }
      {
         vector<Float_t> &R__stl =  thetay;
         int R__n=(true) ? int(R__stl.size()) : 0;
         R__b << R__n;
         if(R__n) {
            vector<Float_t>::iterator R__k;
            for (R__k = R__stl.begin(); R__k != R__stl.end(); ++R__k) {
            R__b << (*R__k);
            }
         }
      }
      {
         vector<Float_t> &R__stl =  angle;
         int R__n=(true) ? int(R__stl.size()) : 0;
         R__b << R__n;
         if(R__n) {
            vector<Float_t>::iterator R__k;
            for (R__k = R__stl.begin(); R__k != R__stl.end(); ++R__k) {
            R__b << (*R__k);
            }
         }
      }
      {
         vector<Int_t> &R__stl =  ing_startmod;
         int R__n=(true) ? int(R__stl.size()) : 0;
         R__b << R__n;
         if(R__n) {
            vector<Int_t>::iterator R__k;
            for (R__k = R__stl.begin(); R__k != R__stl.end(); ++R__k) {
            R__b << (*R__k);
            }
         }
      }
      {
         vector<Int_t> &R__stl =  ing_endmod;
         int R__n=(true) ? int(R__stl.size()) : 0;
         R__b << R__n;
         if(R__n) {
            vector<Int_t>::iterator R__k;
            for (R__k = R__stl.begin(); R__k != R__stl.end(); ++R__k) {
            R__b << (*R__k);
            }
         }
      }
      {
         vector<Int_t> &R__stl =  ing_startpln;
         int R__n=(true) ? int(R__stl.size()) : 0;
         R__b << R__n;
         if(R__n) {
            vector<Int_t>::iterator R__k;
            for (R__k = R__stl.begin(); R__k != R__stl.end(); ++R__k) {
            R__b << (*R__k);
            }
         }
      }
      {
         vector<Int_t> &R__stl =  ing_endpln;
         int R__n=(true) ? int(R__stl.size()) : 0;
         R__b << R__n;
         if(R__n) {
            vector<Int_t>::iterator R__k;
            for (R__k = R__stl.begin(); R__k != R__stl.end(); ++R__k) {
            R__b << (*R__k);
            }
         }
      }
      {
         vector<Bool_t> &R__stl =  ing_trk;
         int R__n=(true) ? int(R__stl.size()) : 0;
         R__b << R__n;
         if(R__n) {
            vector<Bool_t>::iterator R__k;
            for (R__k = R__stl.begin(); R__k != R__stl.end(); ++R__k) {
            R__b << (*R__k);
            }
         }
      }
      {
         vector<Bool_t> &R__stl =  pm_stop;
         int R__n=(true) ? int(R__stl.size()) : 0;
         R__b << R__n;
         if(R__n) {
            vector<Bool_t>::iterator R__k;
            for (R__k = R__stl.begin(); R__k != R__stl.end(); ++R__k) {
            R__b << (*R__k);
            }
         }
      }
      {
         vector<Bool_t> &R__stl =  ing_stop;
         int R__n=(true) ? int(R__stl.size()) : 0;
         R__b << R__n;
         if(R__n) {
            vector<Bool_t>::iterator R__k;
            for (R__k = R__stl.begin(); R__k != R__stl.end(); ++R__k) {
            R__b << (*R__k);
            }
         }
      }
      {
         vector<Float_t> &R__stl =  sci_range;
         int R__n=(true) ? int(R__stl.size()) : 0;
         R__b << R__n;
         if(R__n) {
            vector<Float_t>::iterator R__k;
            for (R__k = R__stl.begin(); R__k != R__stl.end(); ++R__k) {
            R__b << (*R__k);
            }
         }
      }
      {
         vector<Float_t> &R__stl =  iron_range;
         int R__n=(true) ? int(R__stl.size()) : 0;
         R__b << R__n;
         if(R__n) {
            vector<Float_t>::iterator R__k;
            for (R__k = R__stl.begin(); R__k != R__stl.end(); ++R__k) {
            R__b << (*R__k);
            }
         }
      }
      {
         vector<Int_t> &R__stl =  iron_pene;
         int R__n=(true) ? int(R__stl.size()) : 0;
         R__b << R__n;
         if(R__n) {
            vector<Int_t>::iterator R__k;
            for (R__k = R__stl.begin(); R__k != R__stl.end(); ++R__k) {
            R__b << (*R__k);
            }
         }
      }
      {
         vector<Bool_t> &R__stl =  veto;
         int R__n=(true) ? int(R__stl.size()) : 0;
         R__b << R__n;
         if(R__n) {
            vector<Bool_t>::iterator R__k;
            for (R__k = R__stl.begin(); R__k != R__stl.end(); ++R__k) {
            R__b << (*R__k);
            }
         }
      }
      {
         vector<Bool_t> &R__stl =  edge;
         int R__n=(true) ? int(R__stl.size()) : 0;
         R__b << R__n;
         if(R__n) {
            vector<Bool_t>::iterator R__k;
            for (R__k = R__stl.begin(); R__k != R__stl.end(); ++R__k) {
            R__b << (*R__k);
            }
         }
      }
      {
         vector<Int_t> &R__stl =  pdg;
         int R__n=(true) ? int(R__stl.size()) : 0;
         R__b << R__n;
         if(R__n) {
            vector<Int_t>::iterator R__k;
            for (R__k = R__stl.begin(); R__k != R__stl.end(); ++R__k) {
            R__b << (*R__k);
            }
         }
      }
      {
         vector<Float_t> &R__stl =  mucl;
         int R__n=(true) ? int(R__stl.size()) : 0;
         R__b << R__n;
         if(R__n) {
            vector<Float_t>::iterator R__k;
            for (R__k = R__stl.begin(); R__k != R__stl.end(); ++R__k) {
            R__b << (*R__k);
            }
         }
      }
      {
         vector<Float_t> &R__stl =  trkpe;
         int R__n=(true) ? int(R__stl.size()) : 0;
         R__b << R__n;
         if(R__n) {
            vector<Float_t>::iterator R__k;
            for (R__k = R__stl.begin(); R__k != R__stl.end(); ++R__k) {
            R__b << (*R__k);
            }
         }
      }
      R__b << nhits;
      R__b.WriteArray(nhitTs, 10);
      int R__i;
      for (R__i = 0; R__i < 1000; R__i++)
         fIngridHit[R__i].Streamer(R__b);
      for (R__i = 0; R__i < 10; R__i++)
         fTrack[R__i].Streamer(R__b);
      for (R__i = 0; R__i < 10000; R__i++)
         fIngridHitTrk[0][R__i].Streamer(R__b);
      R__b << ntracks;
      R__b.SetByteCount(R__c, kTRUE);
   }
}

//______________________________________________________________________________
void PMAnaSummary::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class PMAnaSummary.
      TClass *R__cl = ::PMAnaSummary::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "Ntrack", &Ntrack);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "Ningtrack", &Ningtrack);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "clstime", &clstime);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "clstimecorr", &clstimecorr);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "exptime", &exptime);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "hitcyc", &hitcyc);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "ontime", &ontime);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "vetowtracking", &vetowtracking);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "edgewtracking", &edgewtracking);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "vact[100]", vact);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "x", (void*)&x);
      R__insp.InspectMember("vector<Float_t>", (void*)&x, "x.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "y", (void*)&y);
      R__insp.InspectMember("vector<Float_t>", (void*)&y, "y.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "z", (void*)&z);
      R__insp.InspectMember("vector<Float_t>", (void*)&z, "z.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "zx", (void*)&zx);
      R__insp.InspectMember("vector<Float_t>", (void*)&zx, "zx.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "zy", (void*)&zy);
      R__insp.InspectMember("vector<Float_t>", (void*)&zy, "zy.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "startxpln", (void*)&startxpln);
      R__insp.InspectMember("vector<Int_t>", (void*)&startxpln, "startxpln.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "startypln", (void*)&startypln);
      R__insp.InspectMember("vector<Int_t>", (void*)&startypln, "startypln.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "startxch", (void*)&startxch);
      R__insp.InspectMember("vector<Float_t>", (void*)&startxch, "startxch.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "startych", (void*)&startych);
      R__insp.InspectMember("vector<Float_t>", (void*)&startych, "startych.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "endxpln", (void*)&endxpln);
      R__insp.InspectMember("vector<Int_t>", (void*)&endxpln, "endxpln.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "endypln", (void*)&endypln);
      R__insp.InspectMember("vector<Int_t>", (void*)&endypln, "endypln.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "endxch", (void*)&endxch);
      R__insp.InspectMember("vector<Float_t>", (void*)&endxch, "endxch.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "endych", (void*)&endych);
      R__insp.InspectMember("vector<Float_t>", (void*)&endych, "endych.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "thetax", (void*)&thetax);
      R__insp.InspectMember("vector<Float_t>", (void*)&thetax, "thetax.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "thetay", (void*)&thetay);
      R__insp.InspectMember("vector<Float_t>", (void*)&thetay, "thetay.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "angle", (void*)&angle);
      R__insp.InspectMember("vector<Float_t>", (void*)&angle, "angle.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "ing_startmod", (void*)&ing_startmod);
      R__insp.InspectMember("vector<Int_t>", (void*)&ing_startmod, "ing_startmod.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "ing_endmod", (void*)&ing_endmod);
      R__insp.InspectMember("vector<Int_t>", (void*)&ing_endmod, "ing_endmod.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "ing_startpln", (void*)&ing_startpln);
      R__insp.InspectMember("vector<Int_t>", (void*)&ing_startpln, "ing_startpln.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "ing_endpln", (void*)&ing_endpln);
      R__insp.InspectMember("vector<Int_t>", (void*)&ing_endpln, "ing_endpln.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "ing_trk", (void*)&ing_trk);
      R__insp.InspectMember("vector<Bool_t>", (void*)&ing_trk, "ing_trk.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "pm_stop", (void*)&pm_stop);
      R__insp.InspectMember("vector<Bool_t>", (void*)&pm_stop, "pm_stop.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "ing_stop", (void*)&ing_stop);
      R__insp.InspectMember("vector<Bool_t>", (void*)&ing_stop, "ing_stop.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "sci_range", (void*)&sci_range);
      R__insp.InspectMember("vector<Float_t>", (void*)&sci_range, "sci_range.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "iron_range", (void*)&iron_range);
      R__insp.InspectMember("vector<Float_t>", (void*)&iron_range, "iron_range.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "iron_pene", (void*)&iron_pene);
      R__insp.InspectMember("vector<Int_t>", (void*)&iron_pene, "iron_pene.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "veto", (void*)&veto);
      R__insp.InspectMember("vector<Bool_t>", (void*)&veto, "veto.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "edge", (void*)&edge);
      R__insp.InspectMember("vector<Bool_t>", (void*)&edge, "edge.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "pdg", (void*)&pdg);
      R__insp.InspectMember("vector<Int_t>", (void*)&pdg, "pdg.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "mucl", (void*)&mucl);
      R__insp.InspectMember("vector<Float_t>", (void*)&mucl, "mucl.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "trkpe", (void*)&trkpe);
      R__insp.InspectMember("vector<Float_t>", (void*)&trkpe, "trkpe.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "nhits", &nhits);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "nhitTs[10]", nhitTs);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fIngridHit[1000]", fIngridHit);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fTrack[10]", fTrack);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fIngridHitTrk[1000][10]", fIngridHitTrk);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "ntracks", &ntracks);
      TObject::ShowMembers(R__insp);
}

namespace ROOTDict {
   // Wrappers around operator new
   static void *new_PMAnaSummary(void *p) {
      return  p ? new(p) ::PMAnaSummary : new ::PMAnaSummary;
   }
   static void *newArray_PMAnaSummary(Long_t nElements, void *p) {
      return p ? new(p) ::PMAnaSummary[nElements] : new ::PMAnaSummary[nElements];
   }
   // Wrapper around operator delete
   static void delete_PMAnaSummary(void *p) {
      delete ((::PMAnaSummary*)p);
   }
   static void deleteArray_PMAnaSummary(void *p) {
      delete [] ((::PMAnaSummary*)p);
   }
   static void destruct_PMAnaSummary(void *p) {
      typedef ::PMAnaSummary current_t;
      ((current_t*)p)->~current_t();
   }
   // Wrapper around a custom streamer member function.
   static void streamer_PMAnaSummary(TBuffer &buf, void *obj) {
      ((::PMAnaSummary*)obj)->::PMAnaSummary::Streamer(buf);
   }
} // end of namespace ROOTDict for class ::PMAnaSummary

namespace ROOTDict {
   void vectorlEboolgR_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void vectorlEboolgR_Dictionary();
   static void *new_vectorlEboolgR(void *p = 0);
   static void *newArray_vectorlEboolgR(Long_t size, void *p);
   static void delete_vectorlEboolgR(void *p);
   static void deleteArray_vectorlEboolgR(void *p);
   static void destruct_vectorlEboolgR(void *p);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const vector<bool>*)
   {
      vector<bool> *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(vector<bool>),0);
      static ::ROOT::TGenericClassInfo 
         instance("vector<bool>", -2, "vectorbool.dll", 0,
                  typeid(vector<bool>), ::ROOT::DefineBehavior(ptr, ptr),
                  0, &vectorlEboolgR_Dictionary, isa_proxy, 0,
                  sizeof(vector<bool>) );
      instance.SetNew(&new_vectorlEboolgR);
      instance.SetNewArray(&newArray_vectorlEboolgR);
      instance.SetDelete(&delete_vectorlEboolgR);
      instance.SetDeleteArray(&deleteArray_vectorlEboolgR);
      instance.SetDestructor(&destruct_vectorlEboolgR);
      instance.AdoptCollectionProxyInfo( ::ROOT::TCollectionProxyInfo::Generate( ::ROOT::TCollectionProxyInfo::Pushback< vector<bool> >()));
      return &instance;
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const vector<bool>*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void vectorlEboolgR_Dictionary() {
      ::ROOTDict::GenerateInitInstanceLocal((const vector<bool>*)0x0)->GetClass();
   }

} // end of namespace ROOTDict

namespace ROOTDict {
   // Wrappers around operator new
   static void *new_vectorlEboolgR(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<bool> : new vector<bool>;
   }
   static void *newArray_vectorlEboolgR(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<bool>[nElements] : new vector<bool>[nElements];
   }
   // Wrapper around operator delete
   static void delete_vectorlEboolgR(void *p) {
      delete ((vector<bool>*)p);
   }
   static void deleteArray_vectorlEboolgR(void *p) {
      delete [] ((vector<bool>*)p);
   }
   static void destruct_vectorlEboolgR(void *p) {
      typedef vector<bool> current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOTDict for class vector<bool>

namespace ROOTDict {
   void vectorlEfloatgR_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void vectorlEfloatgR_Dictionary();
   static void *new_vectorlEfloatgR(void *p = 0);
   static void *newArray_vectorlEfloatgR(Long_t size, void *p);
   static void delete_vectorlEfloatgR(void *p);
   static void deleteArray_vectorlEfloatgR(void *p);
   static void destruct_vectorlEfloatgR(void *p);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const vector<float>*)
   {
      vector<float> *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(vector<float>),0);
      static ::ROOT::TGenericClassInfo 
         instance("vector<float>", -2, "vector.dll", 0,
                  typeid(vector<float>), ::ROOT::DefineBehavior(ptr, ptr),
                  0, &vectorlEfloatgR_Dictionary, isa_proxy, 0,
                  sizeof(vector<float>) );
      instance.SetNew(&new_vectorlEfloatgR);
      instance.SetNewArray(&newArray_vectorlEfloatgR);
      instance.SetDelete(&delete_vectorlEfloatgR);
      instance.SetDeleteArray(&deleteArray_vectorlEfloatgR);
      instance.SetDestructor(&destruct_vectorlEfloatgR);
      instance.AdoptCollectionProxyInfo( ::ROOT::TCollectionProxyInfo::Generate( ::ROOT::TCollectionProxyInfo::Pushback< vector<float> >()));
      return &instance;
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const vector<float>*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void vectorlEfloatgR_Dictionary() {
      ::ROOTDict::GenerateInitInstanceLocal((const vector<float>*)0x0)->GetClass();
   }

} // end of namespace ROOTDict

namespace ROOTDict {
   // Wrappers around operator new
   static void *new_vectorlEfloatgR(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<float> : new vector<float>;
   }
   static void *newArray_vectorlEfloatgR(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<float>[nElements] : new vector<float>[nElements];
   }
   // Wrapper around operator delete
   static void delete_vectorlEfloatgR(void *p) {
      delete ((vector<float>*)p);
   }
   static void deleteArray_vectorlEfloatgR(void *p) {
      delete [] ((vector<float>*)p);
   }
   static void destruct_vectorlEfloatgR(void *p) {
      typedef vector<float> current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOTDict for class vector<float>

namespace ROOTDict {
   void vectorlEintgR_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void vectorlEintgR_Dictionary();
   static void *new_vectorlEintgR(void *p = 0);
   static void *newArray_vectorlEintgR(Long_t size, void *p);
   static void delete_vectorlEintgR(void *p);
   static void deleteArray_vectorlEintgR(void *p);
   static void destruct_vectorlEintgR(void *p);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const vector<int>*)
   {
      vector<int> *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(vector<int>),0);
      static ::ROOT::TGenericClassInfo 
         instance("vector<int>", -2, "prec_stl/vector", 49,
                  typeid(vector<int>), ::ROOT::DefineBehavior(ptr, ptr),
                  0, &vectorlEintgR_Dictionary, isa_proxy, 0,
                  sizeof(vector<int>) );
      instance.SetNew(&new_vectorlEintgR);
      instance.SetNewArray(&newArray_vectorlEintgR);
      instance.SetDelete(&delete_vectorlEintgR);
      instance.SetDeleteArray(&deleteArray_vectorlEintgR);
      instance.SetDestructor(&destruct_vectorlEintgR);
      instance.AdoptCollectionProxyInfo( ::ROOT::TCollectionProxyInfo::Generate( ::ROOT::TCollectionProxyInfo::Pushback< vector<int> >()));
      return &instance;
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const vector<int>*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void vectorlEintgR_Dictionary() {
      ::ROOTDict::GenerateInitInstanceLocal((const vector<int>*)0x0)->GetClass();
   }

} // end of namespace ROOTDict

namespace ROOTDict {
   // Wrappers around operator new
   static void *new_vectorlEintgR(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<int> : new vector<int>;
   }
   static void *newArray_vectorlEintgR(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<int>[nElements] : new vector<int>[nElements];
   }
   // Wrapper around operator delete
   static void delete_vectorlEintgR(void *p) {
      delete ((vector<int>*)p);
   }
   static void deleteArray_vectorlEintgR(void *p) {
      delete [] ((vector<int>*)p);
   }
   static void destruct_vectorlEintgR(void *p) {
      typedef vector<int> current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOTDict for class vector<int>

/********************************************************
* PMAnaSummaryDict.cc
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtablePMAnaSummaryDict();

extern "C" void G__set_cpp_environmentPMAnaSummaryDict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("./PMAnaSummary.h");
  G__cpp_reset_tagtablePMAnaSummaryDict();
}
#include <new>
extern "C" int G__cpp_dllrevPMAnaSummaryDict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* PMAnaSummary */
static int G__PMAnaSummaryDict_204_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   PMAnaSummary* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new PMAnaSummary[n];
     } else {
       p = new((void*) gvp) PMAnaSummary[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new PMAnaSummary;
     } else {
       p = new((void*) gvp) PMAnaSummary;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__PMAnaSummaryDictLN_PMAnaSummary));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PMAnaSummaryDict_204_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   PMAnaSummary* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 1
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new PMAnaSummary(*(PMAnaSummary*) libp->para[0].ref);
   } else {
     p = new((void*) gvp) PMAnaSummary(*(PMAnaSummary*) libp->para[0].ref);
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__PMAnaSummaryDictLN_PMAnaSummary));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PMAnaSummaryDict_204_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((PMAnaSummary*) G__getstructoffset())->Print();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PMAnaSummaryDict_204_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((PMAnaSummary*) G__getstructoffset())->AddIngridHit((IngridHitSummary*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PMAnaSummaryDict_204_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((const PMAnaSummary*) G__getstructoffset())->GetIngridHit((int) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PMAnaSummaryDict_204_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((PMAnaSummary*) G__getstructoffset())->AddIngridHitTrk((IngridHitSummary*) G__int(libp->para[0]), (int) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PMAnaSummaryDict_204_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((const PMAnaSummary*) G__getstructoffset())->GetIngridHitTrk((int) G__int(libp->para[0]), (int) G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PMAnaSummaryDict_204_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((PMAnaSummary*) G__getstructoffset())->AddTrack((IngridTrackSummary*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PMAnaSummaryDict_204_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((const PMAnaSummary*) G__getstructoffset())->GetTrack((int) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PMAnaSummaryDict_204_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((PMAnaSummary*) G__getstructoffset())->Nhits());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PMAnaSummaryDict_204_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((PMAnaSummary*) G__getstructoffset())->NhitTs((int) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PMAnaSummaryDict_204_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((PMAnaSummary*) G__getstructoffset())->Ntracks());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PMAnaSummaryDict_204_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) PMAnaSummary::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PMAnaSummaryDict_204_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) PMAnaSummary::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PMAnaSummaryDict_204_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) PMAnaSummary::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PMAnaSummaryDict_204_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      PMAnaSummary::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PMAnaSummaryDict_204_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((PMAnaSummary*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PMAnaSummaryDict_204_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) PMAnaSummary::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PMAnaSummaryDict_204_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) PMAnaSummary::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PMAnaSummaryDict_204_0_24(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) PMAnaSummary::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PMAnaSummaryDict_204_0_25(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) PMAnaSummary::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef PMAnaSummary G__TPMAnaSummary;
static int G__PMAnaSummaryDict_204_0_26(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (PMAnaSummary*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((PMAnaSummary*) (soff+(sizeof(PMAnaSummary)*i)))->~G__TPMAnaSummary();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (PMAnaSummary*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((PMAnaSummary*) (soff))->~G__TPMAnaSummary();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__PMAnaSummaryDict_204_0_27(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   PMAnaSummary* dest = (PMAnaSummary*) G__getstructoffset();
   *dest = *(PMAnaSummary*) libp->para[0].ref;
   const PMAnaSummary& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* PMAnaSummary */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncPMAnaSummaryDict {
 public:
  G__Sizep2memfuncPMAnaSummaryDict(): p(&G__Sizep2memfuncPMAnaSummaryDict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncPMAnaSummaryDict::*p)();
};

size_t G__get_sizep2memfuncPMAnaSummaryDict()
{
  G__Sizep2memfuncPMAnaSummaryDict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritancePMAnaSummaryDict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__PMAnaSummaryDictLN_PMAnaSummary))) {
     PMAnaSummary *G__Lderived;
     G__Lderived=(PMAnaSummary*)0x1000;
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__PMAnaSummaryDictLN_PMAnaSummary),G__get_linked_tagnum(&G__PMAnaSummaryDictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetablePMAnaSummaryDict() {

   /* Setting up typedef entry */
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__PMAnaSummaryDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__PMAnaSummaryDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__PMAnaSummaryDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__PMAnaSummaryDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__PMAnaSummaryDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__PMAnaSummaryDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__PMAnaSummaryDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__PMAnaSummaryDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__PMAnaSummaryDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__PMAnaSummaryDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__PMAnaSummaryDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__PMAnaSummaryDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__PMAnaSummaryDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__PMAnaSummaryDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__PMAnaSummaryDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<Float_t>",117,G__get_linked_tagnum(&G__PMAnaSummaryDictLN_vectorlEfloatcOallocatorlEfloatgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<Int_t>",117,G__get_linked_tagnum(&G__PMAnaSummaryDictLN_vectorlEintcOallocatorlEintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__PMAnaSummaryDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__PMAnaSummaryDictLN_vectorlEintcOallocatorlEintgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__PMAnaSummaryDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__PMAnaSummaryDictLN_vectorlEintcOallocatorlEintgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<int>",117,G__get_linked_tagnum(&G__PMAnaSummaryDictLN_vectorlEintcOallocatorlEintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<Bool_t>",117,G__get_linked_tagnum(&G__PMAnaSummaryDictLN_vectorlEboolcOallocatorlEboolgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* PMAnaSummary */
static void G__setup_memvarPMAnaSummary(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__PMAnaSummaryDictLN_PMAnaSummary));
   { PMAnaSummary *p; p=(PMAnaSummary*)0x1000; if (p) { }
   G__memvar_setup((void*)((long)(&p->Ntrack)-(long)(p)),105,0,0,-1,-1,-1,1,"Ntrack=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->Ningtrack)-(long)(p)),105,0,0,-1,-1,-1,1,"Ningtrack=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->clstime)-(long)(p)),102,0,0,-1,-1,-1,1,"clstime=",0,"time of cluster defined by most high p.e.");
   G__memvar_setup((void*)((long)(&p->clstimecorr)-(long)(p)),102,0,0,-1,-1,-1,1,"clstimecorr=",0,"time after correction by measurement time of CT");
   G__memvar_setup((void*)((long)(&p->exptime)-(long)(p)),102,0,0,-1,-1,-1,1,"exptime=",0,"diff. from expected time");
   G__memvar_setup((void*)((long)(&p->hitcyc)-(long)(p)),105,0,0,-1,-1,-1,1,"hitcyc=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->ontime)-(long)(p)),103,0,0,-1,-1,-1,1,"ontime=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->vetowtracking)-(long)(p)),103,0,0,-1,-1,-1,1,"vetowtracking=",0,"Upstream VETO");
   G__memvar_setup((void*)((long)(&p->edgewtracking)-(long)(p)),103,0,0,-1,-1,-1,1,"edgewtracking=",0,"Fiducial CUT");
   G__memvar_setup((void*)((long)(&p->vact)-(long)(p)),102,0,0,-1,-1,-1,1,"vact[100]=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->x)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__PMAnaSummaryDictLN_vectorlEfloatcOallocatorlEfloatgRsPgR),G__defined_typename("vector<Float_t>"),-1,1,"x=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->y)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__PMAnaSummaryDictLN_vectorlEfloatcOallocatorlEfloatgRsPgR),G__defined_typename("vector<Float_t>"),-1,1,"y=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->z)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__PMAnaSummaryDictLN_vectorlEfloatcOallocatorlEfloatgRsPgR),G__defined_typename("vector<Float_t>"),-1,1,"z=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->zx)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__PMAnaSummaryDictLN_vectorlEfloatcOallocatorlEfloatgRsPgR),G__defined_typename("vector<Float_t>"),-1,1,"zx=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->zy)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__PMAnaSummaryDictLN_vectorlEfloatcOallocatorlEfloatgRsPgR),G__defined_typename("vector<Float_t>"),-1,1,"zy=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->startxpln)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__PMAnaSummaryDictLN_vectorlEintcOallocatorlEintgRsPgR),G__defined_typename("vector<Int_t>"),-1,1,"startxpln=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->startypln)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__PMAnaSummaryDictLN_vectorlEintcOallocatorlEintgRsPgR),G__defined_typename("vector<Int_t>"),-1,1,"startypln=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->startxch)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__PMAnaSummaryDictLN_vectorlEfloatcOallocatorlEfloatgRsPgR),G__defined_typename("vector<Float_t>"),-1,1,"startxch=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->startych)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__PMAnaSummaryDictLN_vectorlEfloatcOallocatorlEfloatgRsPgR),G__defined_typename("vector<Float_t>"),-1,1,"startych=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->endxpln)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__PMAnaSummaryDictLN_vectorlEintcOallocatorlEintgRsPgR),G__defined_typename("vector<Int_t>"),-1,1,"endxpln=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->endypln)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__PMAnaSummaryDictLN_vectorlEintcOallocatorlEintgRsPgR),G__defined_typename("vector<Int_t>"),-1,1,"endypln=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->endxch)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__PMAnaSummaryDictLN_vectorlEfloatcOallocatorlEfloatgRsPgR),G__defined_typename("vector<Float_t>"),-1,1,"endxch=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->endych)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__PMAnaSummaryDictLN_vectorlEfloatcOallocatorlEfloatgRsPgR),G__defined_typename("vector<Float_t>"),-1,1,"endych=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->thetax)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__PMAnaSummaryDictLN_vectorlEfloatcOallocatorlEfloatgRsPgR),G__defined_typename("vector<Float_t>"),-1,1,"thetax=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->thetay)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__PMAnaSummaryDictLN_vectorlEfloatcOallocatorlEfloatgRsPgR),G__defined_typename("vector<Float_t>"),-1,1,"thetay=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->angle)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__PMAnaSummaryDictLN_vectorlEfloatcOallocatorlEfloatgRsPgR),G__defined_typename("vector<Float_t>"),-1,1,"angle=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->ing_startmod)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__PMAnaSummaryDictLN_vectorlEintcOallocatorlEintgRsPgR),G__defined_typename("vector<Int_t>"),-1,1,"ing_startmod=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->ing_endmod)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__PMAnaSummaryDictLN_vectorlEintcOallocatorlEintgRsPgR),G__defined_typename("vector<Int_t>"),-1,1,"ing_endmod=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->ing_startpln)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__PMAnaSummaryDictLN_vectorlEintcOallocatorlEintgRsPgR),G__defined_typename("vector<Int_t>"),-1,1,"ing_startpln=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->ing_endpln)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__PMAnaSummaryDictLN_vectorlEintcOallocatorlEintgRsPgR),G__defined_typename("vector<Int_t>"),-1,1,"ing_endpln=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->ing_trk)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__PMAnaSummaryDictLN_vectorlEboolcOallocatorlEboolgRsPgR),G__defined_typename("vector<Bool_t>"),-1,1,"ing_trk=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->pm_stop)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__PMAnaSummaryDictLN_vectorlEboolcOallocatorlEboolgRsPgR),G__defined_typename("vector<Bool_t>"),-1,1,"pm_stop=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->ing_stop)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__PMAnaSummaryDictLN_vectorlEboolcOallocatorlEboolgRsPgR),G__defined_typename("vector<Bool_t>"),-1,1,"ing_stop=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->sci_range)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__PMAnaSummaryDictLN_vectorlEfloatcOallocatorlEfloatgRsPgR),G__defined_typename("vector<Float_t>"),-1,1,"sci_range=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->iron_range)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__PMAnaSummaryDictLN_vectorlEfloatcOallocatorlEfloatgRsPgR),G__defined_typename("vector<Float_t>"),-1,1,"iron_range=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->iron_pene)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__PMAnaSummaryDictLN_vectorlEintcOallocatorlEintgRsPgR),G__defined_typename("vector<Int_t>"),-1,1,"iron_pene=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->veto)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__PMAnaSummaryDictLN_vectorlEboolcOallocatorlEboolgRsPgR),G__defined_typename("vector<Bool_t>"),-1,1,"veto=",0,"Upstream VETO");
   G__memvar_setup((void*)((long)(&p->edge)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__PMAnaSummaryDictLN_vectorlEboolcOallocatorlEboolgRsPgR),G__defined_typename("vector<Bool_t>"),-1,1,"edge=",0,"Fiducial CUT");
   G__memvar_setup((void*)((long)(&p->pdg)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__PMAnaSummaryDictLN_vectorlEintcOallocatorlEintgRsPgR),G__defined_typename("vector<Int_t>"),-1,1,"pdg=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->mucl)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__PMAnaSummaryDictLN_vectorlEfloatcOallocatorlEfloatgRsPgR),G__defined_typename("vector<Float_t>"),-1,1,"mucl=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->trkpe)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__PMAnaSummaryDictLN_vectorlEfloatcOallocatorlEfloatgRsPgR),G__defined_typename("vector<Float_t>"),-1,1,"trkpe=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->nhits)-(long)(p)),105,0,0,-1,-1,-1,1,"nhits=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->nhitTs)-(long)(p)),105,0,0,-1,-1,-1,1,"nhitTs[10]=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__PMAnaSummaryDictLN_TRef),-1,-1,4,"fIngridHit[1000]=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__PMAnaSummaryDictLN_TRef),-1,-1,4,"fTrack[10]=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__PMAnaSummaryDictLN_TRef),-1,-1,4,"fIngridHitTrk[1000][10]=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->ntracks)-(long)(p)),105,0,0,-1,-1,-1,1,"ntracks=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__PMAnaSummaryDictLN_TClass),G__defined_typename("atomic_TClass_ptr"),-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarPMAnaSummaryDict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncPMAnaSummary(void) {
   /* PMAnaSummary */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__PMAnaSummaryDictLN_PMAnaSummary));
   G__memfunc_setup("PMAnaSummary",1179,G__PMAnaSummaryDict_204_0_1, 105, G__get_linked_tagnum(&G__PMAnaSummaryDictLN_PMAnaSummary), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("PMAnaSummary",1179,G__PMAnaSummaryDict_204_0_2, 105, G__get_linked_tagnum(&G__PMAnaSummaryDictLN_PMAnaSummary), -1, 0, 1, 1, 1, 0, "u 'PMAnaSummary' - 11 - basicsum", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Clear",487,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "C - 'Option_t' 10 '\"\"' option", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Print",525,G__PMAnaSummaryDict_204_0_4, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("AddIngridHit",1163,G__PMAnaSummaryDict_204_0_5, 121, -1, -1, 0, 1, 1, 1, 0, "U 'IngridHitSummary' - 0 - hit", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetIngridHit",1186,G__PMAnaSummaryDict_204_0_6, 85, G__get_linked_tagnum(&G__PMAnaSummaryDictLN_IngridHitSummary), -1, 0, 1, 1, 1, 8, "i - - 0 - i", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("AddIngridHitTrk",1468,G__PMAnaSummaryDict_204_0_7, 121, -1, -1, 0, 2, 1, 1, 0, 
"U 'IngridHitSummary' - 0 - hit i - - 0 - track", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetIngridHitTrk",1491,G__PMAnaSummaryDict_204_0_8, 85, G__get_linked_tagnum(&G__PMAnaSummaryDictLN_IngridHitSummary), -1, 0, 2, 1, 1, 8, 
"i - - 0 - i i - - 0 - track", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("AddTrack",766,G__PMAnaSummaryDict_204_0_9, 121, -1, -1, 0, 1, 1, 1, 0, "U 'IngridTrackSummary' - 0 - trk", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetTrack",789,G__PMAnaSummaryDict_204_0_10, 85, G__get_linked_tagnum(&G__PMAnaSummaryDictLN_IngridTrackSummary), -1, 0, 1, 1, 1, 8, "i - - 0 - i", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Nhits",518,G__PMAnaSummaryDict_204_0_11, 105, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NhitTs",602,G__PMAnaSummaryDict_204_0_12, 105, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - trk", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Ntracks",726,G__PMAnaSummaryDict_204_0_13, 105, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__PMAnaSummaryDict_204_0_14, 85, G__get_linked_tagnum(&G__PMAnaSummaryDictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&PMAnaSummary::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__PMAnaSummaryDict_204_0_15, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&PMAnaSummary::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__PMAnaSummaryDict_204_0_16, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&PMAnaSummary::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__PMAnaSummaryDict_204_0_17, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&PMAnaSummary::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__PMAnaSummaryDictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__PMAnaSummaryDict_204_0_21, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__PMAnaSummaryDict_204_0_22, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&PMAnaSummary::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__PMAnaSummaryDict_204_0_23, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&PMAnaSummary::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__PMAnaSummaryDict_204_0_24, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&PMAnaSummary::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__PMAnaSummaryDict_204_0_25, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&PMAnaSummary::DeclFileLine) ), 0);
   // automatic destructor
   G__memfunc_setup("~PMAnaSummary", 1305, G__PMAnaSummaryDict_204_0_26, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__PMAnaSummaryDict_204_0_27, (int) ('u'), G__get_linked_tagnum(&G__PMAnaSummaryDictLN_PMAnaSummary), -1, 1, 1, 1, 1, 0, "u 'PMAnaSummary' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncPMAnaSummaryDict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalPMAnaSummaryDict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {
}

static void G__cpp_setup_func20() {
}

static void G__cpp_setup_func21() {
}

static void G__cpp_setup_func22() {
}

static void G__cpp_setup_func23() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcPMAnaSummaryDict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
  G__cpp_setup_func20();
  G__cpp_setup_func21();
  G__cpp_setup_func22();
  G__cpp_setup_func23();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__PMAnaSummaryDictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__PMAnaSummaryDictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__PMAnaSummaryDictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__PMAnaSummaryDictLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__PMAnaSummaryDictLN_vectorlEfloatcOallocatorlEfloatgRsPgR = { "vector<float,allocator<float> >" , 99 , -1 };
G__linked_taginfo G__PMAnaSummaryDictLN_vectorlEboolcOallocatorlEboolgRsPgR = { "vector<bool,allocator<bool> >" , 99 , -1 };
G__linked_taginfo G__PMAnaSummaryDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__PMAnaSummaryDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__PMAnaSummaryDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__PMAnaSummaryDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__PMAnaSummaryDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__PMAnaSummaryDictLN_TRef = { "TRef" , 99 , -1 };
G__linked_taginfo G__PMAnaSummaryDictLN_IngridHitSummary = { "IngridHitSummary" , 99 , -1 };
G__linked_taginfo G__PMAnaSummaryDictLN_IngridTrackSummary = { "IngridTrackSummary" , 99 , -1 };
G__linked_taginfo G__PMAnaSummaryDictLN_PMAnaSummary = { "PMAnaSummary" , 99 , -1 };
G__linked_taginfo G__PMAnaSummaryDictLN_vectorlEintcOallocatorlEintgRsPgR = { "vector<int,allocator<int> >" , 99 , -1 };
G__linked_taginfo G__PMAnaSummaryDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<int,allocator<int> >::iterator>" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtablePMAnaSummaryDict() {
  G__PMAnaSummaryDictLN_TClass.tagnum = -1 ;
  G__PMAnaSummaryDictLN_TBuffer.tagnum = -1 ;
  G__PMAnaSummaryDictLN_TMemberInspector.tagnum = -1 ;
  G__PMAnaSummaryDictLN_TObject.tagnum = -1 ;
  G__PMAnaSummaryDictLN_vectorlEfloatcOallocatorlEfloatgRsPgR.tagnum = -1 ;
  G__PMAnaSummaryDictLN_vectorlEboolcOallocatorlEboolgRsPgR.tagnum = -1 ;
  G__PMAnaSummaryDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__PMAnaSummaryDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__PMAnaSummaryDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__PMAnaSummaryDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__PMAnaSummaryDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__PMAnaSummaryDictLN_TRef.tagnum = -1 ;
  G__PMAnaSummaryDictLN_IngridHitSummary.tagnum = -1 ;
  G__PMAnaSummaryDictLN_IngridTrackSummary.tagnum = -1 ;
  G__PMAnaSummaryDictLN_PMAnaSummary.tagnum = -1 ;
  G__PMAnaSummaryDictLN_vectorlEintcOallocatorlEintgRsPgR.tagnum = -1 ;
  G__PMAnaSummaryDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtablePMAnaSummaryDict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__PMAnaSummaryDictLN_TClass);
   G__get_linked_tagnum_fwd(&G__PMAnaSummaryDictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__PMAnaSummaryDictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__PMAnaSummaryDictLN_TObject);
   G__get_linked_tagnum_fwd(&G__PMAnaSummaryDictLN_vectorlEfloatcOallocatorlEfloatgRsPgR);
   G__get_linked_tagnum_fwd(&G__PMAnaSummaryDictLN_vectorlEboolcOallocatorlEboolgRsPgR);
   G__get_linked_tagnum_fwd(&G__PMAnaSummaryDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__PMAnaSummaryDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__PMAnaSummaryDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__PMAnaSummaryDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__PMAnaSummaryDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G__PMAnaSummaryDictLN_TRef);
   G__get_linked_tagnum_fwd(&G__PMAnaSummaryDictLN_IngridHitSummary);
   G__get_linked_tagnum_fwd(&G__PMAnaSummaryDictLN_IngridTrackSummary);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__PMAnaSummaryDictLN_PMAnaSummary),sizeof(PMAnaSummary),-1,30464,"Ingrid Hit Summary",G__setup_memvarPMAnaSummary,G__setup_memfuncPMAnaSummary);
   G__get_linked_tagnum_fwd(&G__PMAnaSummaryDictLN_vectorlEintcOallocatorlEintgRsPgR);
   G__get_linked_tagnum_fwd(&G__PMAnaSummaryDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR);
}
extern "C" void G__cpp_setupPMAnaSummaryDict(void) {
  G__check_setup_version(30051515,"G__cpp_setupPMAnaSummaryDict()");
  G__set_cpp_environmentPMAnaSummaryDict();
  G__cpp_setup_tagtablePMAnaSummaryDict();

  G__cpp_setup_inheritancePMAnaSummaryDict();

  G__cpp_setup_typetablePMAnaSummaryDict();

  G__cpp_setup_memvarPMAnaSummaryDict();

  G__cpp_setup_memfuncPMAnaSummaryDict();
  G__cpp_setup_globalPMAnaSummaryDict();
  G__cpp_setup_funcPMAnaSummaryDict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncPMAnaSummaryDict();
  return;
}
class G__cpp_setup_initPMAnaSummaryDict {
  public:
    G__cpp_setup_initPMAnaSummaryDict() { G__add_setup_func("PMAnaSummaryDict",(G__incsetup)(&G__cpp_setupPMAnaSummaryDict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initPMAnaSummaryDict() { G__remove_setup_func("PMAnaSummaryDict"); }
};
G__cpp_setup_initPMAnaSummaryDict G__cpp_setup_initializerPMAnaSummaryDict;

